#!/usr/bin/env bash
set -e

typing=true
for i in "$@"; do
    case $i in
        --no-typing)
        typing=false
        shift
        ;;
    esac
done

. env/bin/activate
if [ "$typing" = true ]; then
    mypy --install-types --non-interactive --strict -p app 2>&1
fi
find ./app -not \( -path "*env/*" -prune \) -type f -name '*.py' | xargs pylint
